### ISSUE TITLE
Unable to open built or deployed site

### ISSUE THREAD

**Issue by saamerm** [anaikarsaad/beaware#28]
When I try to open the built/deployed site, I see a blank screen

**Comment by anaikarsaad** [comment]
Hi sameer the deployed site won’t work because now our app is dependent on the localhost for the api and its not upto date with the local code i will go ahead the merge all changes to mail still the won’t be fully functional on the deployed site this can be fixed by replacing localhost api with your actual apis
If you need more assistance 
Mobile :905 324 9706

**Comment by saamerm** [comment]
Hi @anaikarsaad the API fails against your local host because of security purposes of what the "origin" value can be for the API call. Once deployed to https://app.deafassistant.com it will work
So don't worry about the API failing, just take a look at what's failing when I try to run a build or when I try to deploy to firebase, why it's showing a blank screen

**Comment by anaikarsaad** [comment]
I have pushed my latest code that works for me locally it should work as expected now

**Comment by saamerm** [comment]
Using what you shared, I tried to do a `firebase deploy` using my account but I get a blank screen as you can see here https://beawareconfcapportal.web.app/

Are you able to deploy to firebase?

**Comment by saamerm** [comment]
@anaikarsaad ^

**Comment by saamerm** [comment]
Ah I figured it out! Works now
My firebase.json had to say `"public": "build",`

**Comment by saamerm** [comment]
App is live on app.deafassistant.com
